version: '3.4'

services:
  microserviceexample.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5200:80"
  microserviceexample.healthchecks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5204:80"
  microserviceexample.userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=microserviceexample.sqlserver;Database=MicroServiceExample;User Id=sa;Password=Micr0ServiceEx@mpl3
    ports:
      - "5202:80"
  microserviceexample.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5201:80"
  microserviceexample.sqlserver:
    environment:
      - SA_PASSWORD=Micr0ServiceEx@mpl3
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
